const { writeFileSync } = require("fs");
const p = "E:/ap/AgentPrimordia/sdk/typescript/tests/unit/turn-executor.test.ts";
const c = [];
c.push("import { describe, it, expect } from 'vitest';");
c.push("import { TurnExecutor } from '../../src/agent/turn-executor.js';");
c.push("import type { CapabilitiesCache, TurnState } from '../../src/agent/turn-executor.js';");
c.push("import type { ToolCall } from '../../src/types.js';");
c.push("import { MockProvider } from '../../src/llm/provider.js';");
c.push("import { ToolRegistry } from '../../src/tools/registry.js';");
c.push("import { HookManager } from '../../src/agent/hooks.js';");
c.push("");
c.push("function createState(): TurnState {");
c.push("  return { consecutiveFailures: 0, totalLLMLatency: 0, totalToolLatency: 0, toolCount: 0, pendingMemoryWrites: [] };");
c.push("}");
c.push("");
c.push("const emptyCapCache: CapabilitiesCache = { costTracker: null, memoryStore: null, checkpointStore: null, otelBridge: null };");
c.push("");
c.push("function createTool(name: string) {");
c.push("  return { type: 'function' as const, function: { name, description: 'desc', parameters: {} } };");
c.push("}");
c.push("");
c.push("function makeExecutor(response: string, opts: { toolCalls?: ToolCall[]; hooks?: HookManager; tools?: any[] } = {}) {");
c.push("  const provider = new MockProvider({ response, toolCalls: opts.toolCalls });");
c.push("  const registry = new ToolRegistry();");
c.push("  for (const t of opts.tools || []) registry.register(t);");
c.push("  return new TurnExecutor(provider as unknown as any, registry, opts.hooks || new HookManager(), emptyCapCache,");
c.push("    { name: 'test', sessionId: 'test-session', maxConsecutiveFailures: 3, parallelToolExecution: false, maxParallelTools: 0, maxMessages: 80 });");
c.push("}");
c.push("");
c.push("describe('TurnExecutor', () => {");
c.push("  describe('executeTurn - basic', () => {");
c.push("    it('completes a turn without tools', async () => {");
c.push("      const executor = makeExecutor('Hello!');");
c.push("      const result = await executor.executeTurn([{ role: 'user', content: 'Hi' }], 0, createState(), Date.now());");
c.push("      expect(result.response?.content).toBe('Hello!');");
c.push("    });");
c.push("");
c.push("    it('shouldStop when no tool calls', async () => {");
c.push("      const executor = makeExecutor('Done');");
c.push("      const result = await executor.executeTurn([{ role: 'user' as const, content: 'q' }], 0, createState(), Date.now());");
c.push("      expect(result.shouldStop).toBe(true);");
c.push("    });");
c.push("");
c.push("    it('should append assistant message to messages', async () => {");
c.push("      const executor = makeExecutor('Response');");
c.push("      const messages = [{ role: 'user' as const, content: 'Q' }];");
c.push("      await executor.executeTurn(messages, 0, createState(), Date.now());");
c.push("      expect(messages.length).toBeGreaterThanOrEqual(2);");
c.push("    });");
c.push("  });");
c.push("");
c.push("  describe('executeTurn - tools', () => {");
c.push("    it('should execute tools and continue (not stop)', async () => {");
c.push("      const toolCalls: ToolCall[] = [{ id: 'tc1', name: 'echo', arguments: '{}' }];");
c.push("      const executor = makeExecutor('tool result', { toolCalls, tools: [createTool('echo')] });");
c.push("      const result = await executor.executeTurn([{ role: 'user' as const, content: 'call' }], 0, createState(), Date.now());");
c.push("      expect(result.shouldStop).toBe(false);");
c.push("      expect(result.tools?.executed).toBe(1);");
c.push("    });");
c.push("");
c.push("    it('should update tool count in state', async () => {");
c.push("      const toolCalls: ToolCall[] = [{ id: 'tc1', name: 'echo', arguments: '{}' }];");
c.push("      const state = createState();");
c.push("      const executor = makeExecutor('result', { toolCalls, tools: [createTool('echo')] });");
c.push("      await executor.executeTurn([{ role: 'user' as const, content: 'go' }], 0, state, Date.now());");
c.push("      expect(state.toolCount).toBe(1);");
c.push("    });");
c.push("");
c.push("    it('should handle tool not found', async () => {");
c.push("      const toolCalls: ToolCall[] = [{ id: 'tc1', name: 'nonexistent', arguments: '{}' }];");
c.push("      const state = createState();");
c.push("      const executor = makeExecutor('fail', { toolCalls, tools: [] });");
c.push("      await executor.executeTurn([{ role: 'user' as const, content: 'err' }], 0, state, Date.now());");
c.push("      expect(state.consecutiveFailures).toBeGreaterThanOrEqual(1);");
c.push("    });");
c.push("  });");
c.push("");
c.push("  describe('hooks', () => {");
c.push("    it('should trigger before_turn, after_llm, on_complete and after_turn', async () => {");
c.push("      const hooks = new HookManager();");
c.push("      const calls: string[] = [];");
c.push("      hooks.register('before_turn', () => calls.push('before_turn'));");
c.push("      hooks.register('after_llm', () => calls.push('after_llm'));");
c.push("      hooks.register('on_complete', () => calls.push('on_complete'));");
c.push("      hooks.register('after_turn', () => calls.push('after_turn'));");
c.push("      const executor = makeExecutor('done', { hooks });");
c.push("      await executor.executeTurn([{ role: 'user' as const, content: 'hi' }], 0, createState(), Date.now());");
c.push("      expect(calls).toContain('before_turn');");
c.push("      expect(calls).toContain('after_llm');");
c.push("      expect(calls).toContain('on_complete');");
c.push("      expect(calls).toContain('after_turn');");
c.push("    });");
c.push("  });");
c.push("");
c.push("  describe('error handling', () => {");
c.push("    it('should propagate LLM error', async () => {");
c.push("      const provider = new MockProvider({ response: 'err', error: true });");
c.push("      const registry = new ToolRegistry();");
c.push("      const executor = new TurnExecutor(provider as unknown as any, registry, new HookManager(), emptyCapCache,");
c.push("        { name: 'test', sessionId: 'test-session', maxConsecutiveFailures: 3, parallelToolExecution: false, maxParallelTools: 0, maxMessages: 80 });");
c.push("      await expect(executor.executeTurn([{ role: 'user' as const, content: 'err' }], 0, createState(), Date.now())).rejects.toThrow();");
c.push("    });");
c.push("  });");
c.push("});");
c.push("");
writeFileSync(p, c.join("\n"), "utf-8");
console.log("Written. Lines: " + c.length);