/**
 * 代码生成器 - 根据模板生成 TypeScript 源代码
 *
 * 支持三种模板类型：
 * - Tool: 生成工具定义类及其 Zod schema
 * - Agent: 生成 ReAct Agent 子类
 * - Provider: 生成 LLM Provider 骨架
 *
 * 生成的代码包含完整 JSDoc 注释，可直接通过 tsc --noEmit 验证。
 */

import type { ToolTemplate } from './templates/tool.js';
import type { AgentTemplateConfig } from './templates/agent.js';
import type { ProviderTemplateConfig } from './templates/provider.js';

export type { ToolTemplate } from './templates/tool.js';
export type { AgentTemplateConfig } from './templates/agent.js';
export type { ProviderTemplateConfig } from './templates/provider.js';

/** 代码生成器 */
export class CodeGenerator {
  /**
   * 生成 TypeScript 工具定义代码
   *
   * @param template - 工具模板配置
   * @returns 完整的 TypeScript 工具类源代码
   */
  generateTool(template: ToolTemplate): string {
    const className = this.toPascalCase(template.name) + 'Tool';
    const schemaName = this.toCamelCase(template.name) + 'Schema';

    const params = Object.entries(template.parameters) as [string, { type: string; description: string; required: boolean }][];
    const requiredParams = params.filter(([, p]) => p.required);

    // 生成 Zod schema 字段
    const schemaFields = params.map(([key, p]) => {
      const base = this.zodType(p.type);
      const desc = p.description ? `.describe('${this.escapeStr(p.description)}')` : '';
      return `  ${key}: z.${base}${desc}`;
    }).join(',\n');

    // 生成参数文档注释
    const paramDocs = params.map(([key, p]) => {
      return `   * @param ${key} - ${p.description} ${p.required ? '(必填)' : '(可选)'}`;
    }).join('\n');

    // 生成 execute 方法体
    const execBody = params.map(([key]) => `      ${key}: args.${key}`).join(',\n');

    // 生成 JSON Schema 属性
    const jsonSchemaProps = params.map(([key, p]) => {
      return `      ${key}: { type: '${p.type}', description: '${this.escapeStr(p.description)}' }`;
    }).join(',\n');

    const requiredKeys = requiredParams.map(([k]) => `'${k}'`).join(', ');
    const hasRequired = requiredKeys.length > 0;

    return `import { z } from 'zod';

/**
 * ${template.description}
 *
 * @generated by AgentPrimordia CodeGenerator
 */
const ${schemaName} = z.object({
${schemaFields}
});

/** ${template.name} 工具的参数类型 */
export type ${className}Params = z.infer<typeof ${schemaName}>;

/**
 * ${template.description}
 *
 * @example
 * const tool = new ${className}();
 * const result = await tool.execute({ /* args */ });
 *
 * @generated by AgentPrimordia CodeGenerator
 */
export class ${className} {
  readonly name = '${template.name}';
  readonly description = '${this.escapeStr(template.description)}';

  /** 工具参数定义 (OpenAI Function Calling 格式) */
  readonly parameters = {
    type: 'object' as const,
    properties: {
${jsonSchemaProps}
    },
    required: [${hasRequired ? requiredKeys : ''}]
  };

  /**
   * 执行工具
${paramDocs}
   * @returns 工具执行结果
   */
  async execute(args: ${className}Params): Promise<string> {
    try {
      const validated = ${schemaName}.parse(args);
      // TODO: 实现具体的工具逻辑
      return this.run({
${execBody}
      });
    } catch (err) {
      if (err instanceof z.ZodError) {
        return \`参数验证失败: \${err.message}\`;
      }
      throw err;
    }
  }

  /**
   * 实际运行逻辑 - 需要覆写或扩展
   * @param args - 已验证的参数
   * @returns 执行结果字符串
   */
  protected run(args: ${className}Params): string | Promise<string> {
    return JSON.stringify(args, null, 2);
  }
}

/** 工具定义 (用于 ToolDefinition 注册) */
export const ${template.name}ToolDefinition = {
  type: 'function' as const,
  function: {
    name: '${template.name}',
    description: '${this.escapeStr(template.description)}',
    parameters: {
      type: 'object',
      properties: {
${jsonSchemaProps}
      },
      required: [${hasRequired ? requiredKeys : ''}]
    }
  }
};
`;
  }

  /**
   * 生成 Agent 类代码
   *
   * @param config - Agent 模板配置
   * @returns 完整的 TypeScript Agent 类源代码
   */
  generateAgent(config: AgentTemplateConfig): string {
    const className = this.toPascalCase(config.name);
    const modelLine = config.model ? `  readonly defaultModel = '${config.model}';\n` : '';
    const toolsLine = config.tools && config.tools.length > 0
      ? `  readonly availableTools = [${config.tools.map((t: string) => `'${t}'`).join(', ')}] as const;\n`
      : '';
    const tempLine = config.temperature !== undefined ? `  readonly temperature = ${config.temperature};\n` : '';
    const maxTokensLine = config.maxTokens ? `  readonly maxTokens = ${config.maxTokens};\n` : '';

    const toolsImport = config.tools && config.tools.length > 0
      ? `\n// 导入所需工具\n${config.tools.map((t: string) => `import { ${this.toPascalCase(t)}Tool } from './tools/${t}';`).join('\n')}\n`
      : '';

    return `import { ReActAgent, type ReActConfig } from './react-loop';
import type { Tool } from './types';
import { MockProvider } from './llm/provider';
${toolsImport}
/**
 * ${config.description}
 *
 * @example
 * const agent = new ${className}({
 *   provider: new MockProvider()
 * });
 * const result = await agent.run('Hello!');
 *
 * @generated by AgentPrimordia CodeGenerator
 */
export class ${className} extends ReActAgent {
  readonly agentName = '${config.name}';${modelLine}${toolsLine}${tempLine}${maxTokensLine}
  /**
   * 创建 ${className} 实例
   * @param config - Agent 配置
   */
  constructor(config?: Partial<ReActConfig>) {
    const tools: Tool[] = [
${config.tools && config.tools.length > 0 ? config.tools.map((t: string) => `      new ${this.toPascalCase(t)}Tool()`).join(',\n') : '      // TODO: 添加工具实例'}
    ];

    super({
      systemPrompt: \`${this.escapeStr(config.systemPrompt)}\`,
      provider: new MockProvider(),
      tools,
      ...config,
    });
  }

  /**
   * 自定义钩子 - 在每次 LLM 调用前执行
   * 覆写此方法添加自定义逻辑
   */
  protected async beforeLLMCall(messages: unknown[]): Promise<void> {
    // TODO: 添加前置处理逻辑
  }

  /**
   * 自定义钩子 - 在每次 LLM 调用后执行
   * 覆写此方法添加自定义逻辑
   */
  protected async afterLLMCall(response: string): Promise<void> {
    // TODO: 添加后置处理逻辑
  }
}

/** 创建 ${className} 实例的工厂函数 */
export function create${className}(config?: Partial<ReActConfig>): ${className} {
  return new ${className}(config);
}
`;
  }

  /**
   * 生成 LLM Provider 骨架代码
   *
   * @param config - Provider 模板配置
   * @returns 完整的 TypeScript Provider 类源代码
   */
  generateProvider(config: ProviderTemplateConfig): string {
    const className = this.toPascalCase(config.name) + 'Provider';
    const versionLine = config.apiVersion ? `  readonly apiVersion = '${config.apiVersion}';\n` : '';

    return `import type { Provider, CompletionRequest, CompletionResponse, Message, Chunk } from './provider';

/**
 * ${config.name} LLM Provider
 *
 * 基于 ${config.baseURL} 实现的 LLM Provider
 *
 * @example
 * const provider = new ${className}({ apiKey: 'your-key' });
 * const response = await provider.complete(request);
 *
 * @generated by AgentPrimordia CodeGenerator
 */
export class ${className} implements Provider {
  readonly name = '${config.name}';
  readonly baseURL = '${config.baseURL}';
  readonly defaultModel = '${config.defaultModel}';${versionLine}
  private apiKey: string;

  constructor(config: { apiKey: string; baseURL?: string }) {
    if (!config.apiKey) {
      throw new Error('${config.name}Provider: apiKey is required');
    }
    this.apiKey = config.apiKey;
  }

  /**
   * 执行非流式补全请求
   * @param request - 补全请求
   * @returns 补全响应
   */
  async complete(request: CompletionRequest): Promise<CompletionResponse> {
    const url = \`\${this.baseURL}/v1/chat/completions\`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': \`Bearer \${this.apiKey}\`,
      },
      body: JSON.stringify({
        model: request.model ?? this.defaultModel,
        messages: request.messages,
        temperature: request.temperature ?? 0.7,
        max_tokens: request.maxTokens,
      }),
    });

    if (!response.ok) {
      throw new Error(\`${config.name}Provider HTTP error: \${response.status}\`);
    }

    const data = await response.json();
    return {
      id: data.id ?? \`${config.name.toLowerCase()}-\${Date.now()}\`,
      content: data.choices?.[0]?.message?.content ?? '',
      role: 'assistant' as const,
      usage: {
        promptTokens: data.usage?.prompt_tokens ?? 0,
        completionTokens: data.usage?.completion_tokens ?? 0,
        totalTokens: data.usage?.total_tokens ?? 0,
      },
    };
  }

  /**
   * 执行流式补全请求
   * @param request - 补全请求
   * @param onChunk - 每个数据块的回调
   */
  async stream(request: CompletionRequest, onChunk: (chunk: Chunk) => void): Promise<void> {
    const url = \`\${this.baseURL}/v1/chat/completions\`;
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': \`Bearer \${this.apiKey}\`,
      },
      body: JSON.stringify({
        model: request.model ?? this.defaultModel,
        messages: request.messages,
        temperature: request.temperature ?? 0.7,
        max_tokens: request.maxTokens,
        stream: true,
      }),
    });

    if (!response.ok) {
      throw new Error(\`${config.name}Provider stream error: \${response.status}\`);
    }

    const reader = response.body?.getReader();
    if (!reader) {
      throw new Error('${config.name}Provider: no response body');
    }

    const decoder = new TextDecoder();
    let buffer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\\n');
      buffer = lines.pop() ?? '';

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || !trimmed.startsWith('data: ')) continue;
        const jsonStr = trimmed.slice(6);
        if (jsonStr === '[DONE]') {
          onChunk({ content: '', done: true });
          return;
        }
        try {
          const parsed = JSON.parse(jsonStr);
          const content = parsed.choices?.[0]?.delta?.content ?? '';
          onChunk({ content, done: false });
        } catch {
          // Skip malformed lines
        }
      }
    }
    onChunk({ content: '', done: true });
  }

  /**
   * 获取可用模型列表
   */
  async listModels(): Promise<string[]> {
    return [this.defaultModel];
  }

  /**
   * 检查当前配置是否可用
   */
  async isAvailable(): Promise<boolean> {
    try {
      await this.listModels();
      return true;
    } catch {
      return false;
    }
  }
}
`;
  }

  // ===== 辅助方法 =====

  /** 转换字符串为大驼峰命名 */
  private toPascalCase(s: string): string {
    return s.replace(/(^|_|-)([a-z])/g, (_, _p, c) => c.toUpperCase()).replace(/[-_]/g, '');
  }

  /** 转换字符串为小驼峰命名 */
  private toCamelCase(s: string): string {
    const pascal = this.toPascalCase(s);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }

  /** 将类型映射到 Zod 方法 */
  private zodType(type: string): string {
    switch (type) {
      case 'string': return 'string()';
      case 'number': return 'number()';
      case 'boolean': return 'boolean()';
      case 'integer': return 'number().int()';
      case 'array': return 'array(z.unknown())';
      case 'object': return 'object({})';
      default: return 'unknown()';
    }
  }

  /** 转义字符串中的特殊字符 */
  private escapeStr(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/`/g, '\\`').replace(/\$/g, '\\$');
  }
}